default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  socket: /tmp/mysqld.sock
  username: root
  password: root
  #socket: /var/run/mysqld/mysqld.sock

development:
  primary:
    <<: *default
    database: emart_reactrailsApi

test:
  <<: *default
  database: emart_reactrailsApi
  username: root
  password: root

staging:
  <<: *default
  database: emart_reactrailsApi
  username: root
  password: root

production:
  <<: *default
  database: emart_reactrailsApi
  username: root
  password: root